// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjkqvbxtziheggurtvcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqa3F2Ynh0emloZWdndXJ0dmN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxMzk4MzUsImV4cCI6MjA4MjcxNTgzNX0.cpxkZ-0bKYfCPUOO6UszMiEoxXPn1d_3xR6_S4QXgQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});